name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.101
    - run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./coverage/opencover.xml
    - run: dotnet publish ./Kossi.Ayedze.FeatureMatching.WebApi/Kossi.Ayedze.FeatureMatching.WebApi.csproj --self-contained true --output ./win-x64/Kossi.Ayedze.FeatureMatching.WebApi -c Release -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true
    - name: Upload WebApp1 Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Publish win-x64 Kossi.Ayedze.FeatureMatching
        path: ./win-x64/Kossi.Ayedze.FeatureMatching  
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
